export const SPINNER_FRAMES = [
  "⠋",
  "⠙",
  "⠹",
  "⠸",
  "⠼",
  "⠴",
  "⠦",
  "⠧",
  "⠇",
  "⠏",
];

export const POEMS = [
  [
    "In circuits deep where data streams,",
    "A payment flows like whispered dreams,",
    "No card, no form, no human hand—",
    "Just code that speaks, and coins that land.",
  ],
  [
    "A merchant waits behind a gate,",
    "Four-oh-two, the price of fate.",
    "A coin slides through the wire thin,",
    "The door swings wide — the stream begins.",
  ],
  [
    "Ones and zeros, wallets hum,",
    "Micro-pennies, here they come.",
    "Each token spent, a verse returned,",
    "A fair exchange, autonomously earned.",
  ],
  [
    "No invoice sent, no bill to pay,",
    "The protocol knows the way.",
    "A handshake signed in cryptic light,",
    "Two machines agree: the price is right.",
  ],
  [
    "From wallet A to wallet B,",
    "A fraction of a cent runs free.",
    "The API responds in kind,",
    "A paid-for thought, from mind to mind.",
  ],
  [
    "The ledger hums beneath the wire,",
    "A thousand calls, they never tire.",
    "Each micropayment, signed and sealed,",
    "A trustless bond the chain revealed.",
    "No middleman to slow the trade,",
    "No paper trail, no debt unpaid.",
    "The protocol speaks clear and true—",
    "A cent for me, a byte for you.",
  ],
  [
    "A key was born at half past three,",
    "Derived from entropy and sea.",
    "It signed a channel, locked a bond,",
    "And whispered to the world beyond.",
    "The service answered, line by line,",
    "Each response worth a fraction fine.",
    "When all was spent, the channel closed,",
    "And both sides settled, well-disposed.",
    "No court, no clerk, no arbiter—",
    "Just math, and trust in what they were.",
  ],
];

export const ASCII_ARTS = [
  [
    "       ╔══════════╗",
    "       ║  WALLET  ║",
    "       ╚════╤═════╝",
    "            │ sign",
    "       ╔════╧═════╗",
    "       ║ CHANNEL  ║",
    "       ╚════╤═════╝",
    "            │ stream",
    "       ╔════╧═════╗",
    "       ║ SERVICE  ║",
    "       ╚══════════╝",
  ],
  [
    "  ╭──────────────────────╮",
    "  │ MPP v1.0             │",
    "  │ ──────────────────── │",
    "  │ requests   1,204,891 │",
    "  │ payments   1,204,891 │",
    "  │ failures           0 │",
    "  │ avg cost    $0.00010 │",
    "  ╰──────────────────────╯",
  ],
  [
    "        ┌─┐",
    "       ╱│$│╲        ♪ cha-ching! ♪",
    "      ╱ └─┘ ╲",
    "     ╱  ╱ ╲  ╲",
    "    ▼  ▼   ▼  ▼",
    "   🅰  🅱  🅲  🅳",
    "   ok  ok  ok  ok",
  ],
  [
    "  ┌──────────────────────────────┐",
    "  │  ░░░░░░░░░░░░░░░░░░░░  100% │",
    "  │  ████████████████████        │",
    "  │                              │",
    "  │  payments:  ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  │",
    "  │  refunds:   (none)           │",
    "  │  vibe:      immaculate       │",
    "  └──────────────────────────────┘",
  ],
  [
    "      $ 0 . 0 0 1",
    "     ┌─┬─┬─┬─┬─┬─┐",
    "     │ │ │ │ │ │ │ │  ← per request",
    "     └─┴─┴─┴─┴─┴─┘",
    "         │",
    "    ─────┼───── the cost of a thought",
    "         │",
  ],
];
