export const SPINNER_FRAMES = [
  "⠋",
  "⠙",
  "⠹",
  "⠸",
  "⠼",
  "⠴",
  "⠦",
  "⠧",
  "⠇",
  "⠏",
];

export const CHAT_RESPONSES = [
  [
    "HTTP 402 is the status code for Payment Required. It was reserved in",
    "HTTP/1.1 but never standardized—until now. MPP defines a challenge-",
    "credential-receipt flow that lets any API monetize with stablecoins.",
    "The server sends a WWW-Authenticate challenge, the client signs a",
    "payment credential, and the server returns a receipt on success.",
    "No API keys, no billing portals, no invoices. Just pay-per-request.",
  ],
  [
    "Micropayments change the economics of APIs. Instead of monthly",
    "subscriptions with usage limits, you pay fractions of a cent per",
    "request. A single GPT-4o call costs about $0.003. An image gen",
    "costs $0.01. Web search is $0.002. The marginal cost is so low",
    "that agents can autonomously decide what to pay for.",
  ],
  [
    "Stablecoins like USDC solve the payment rail problem. They settle",
    "in seconds, cost almost nothing to transfer, and work globally",
    "without bank accounts or currency conversion. When you combine",
    "stablecoins with HTTP-native auth, you get a protocol where any",
    "machine can pay any other machine, anywhere, instantly.",
  ],
  [
    "The key insight is that AI agents need to pay for things. They call",
    "APIs, use compute, fetch data—but they can't enter credit card",
    "numbers. MPP gives agents a wallet and a protocol. The agent signs",
    "a payment, the server verifies it on-chain, and the response streams",
    "back. No human in the loop.",
  ],
  [
    "Payment channels let you batch thousands of micropayments into a",
    "single on-chain settlement. You open a channel, make requests, and",
    "each one increments a signed balance. When you're done, the final",
    "balance settles on-chain. One transaction for a thousand API calls.",
    "Gas costs amortized to nearly zero.",
  ],
  [
    "Think of it like this: every API endpoint has a price, just like",
    "every webpage has a URL. The price lives in the 402 response header.",
    "Clients that understand the protocol pay automatically. Clients that",
    "don't get a standard HTTP error. It's backwards-compatible with the",
    "entire web. No new infrastructure required.",
  ],
  [
    "The authorization header carries a signed payment credential. The",
    "server verifies the signature, checks the amount, and processes the",
    "request. If the payment is valid, you get a 200 with a receipt",
    "header. If not, you get a 402 with a challenge. The whole exchange",
    "takes milliseconds—faster than a credit card authorization.",
  ],
];

export const IMAGE_RESULTS = [
  [
    "  model       flux-schnell",
    '  prompt      "a neon cityscape at night with flying cars"',
    "  url         https://fal.ai/outputs/a7b3c9d2e1f0.png",
    "  size        1024x1024",
    "  cost        $0.003",
  ],
  [
    "  model       flux-schnell",
    '  prompt      "an isometric server room with glowing racks"',
    "  url         https://fal.ai/outputs/f4e8d2c1b5a9.png",
    "  size        1024x1024",
    "  cost        $0.003",
  ],
  [
    "  model       flux-schnell",
    '  prompt      "a robot hand holding a golden coin, macro shot"',
    "  url         https://fal.ai/outputs/c2d9e7f3a1b8.png",
    "  size        1024x1024",
    "  cost        $0.003",
  ],
  [
    "  model       flux-schnell",
    '  prompt      "abstract visualization of blockchain data flow"',
    "  url         https://fal.ai/outputs/b8a1c3d5e9f2.png",
    "  size        1024x1024",
    "  cost        $0.003",
  ],
  [
    "  model       flux-schnell",
    '  prompt      "a minimalist wallet icon on gradient background"',
    "  url         https://fal.ai/outputs/d5e2f8a4c7b1.png",
    "  size        1024x1024",
    "  cost        $0.003",
  ],
];

export const SEARCH_RESULTS = [
  [
    "  (Simulated results — connect a live API key for real search)",
    "",
    "  1. HTTP 402 Payment Required — MDN Web Docs",
    "     https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402",
    "     The 402 status code is reserved for future use in digital payment",
    "     systems. Originally defined in HTTP/1.1, it was never standardized.",
    "",
    "  2. Machine Payment Protocol Specification",
    "     https://mppx.dev/specs/core",
    "     MPP defines a challenge-credential-receipt flow for HTTP-native",
    "     payments using stablecoins on EVM-compatible chains.",
    "",
    "  3. The Economics of API Micropayments",
    "     https://a]16z.com/micropayments-api-economy",
    "     Why fractions-of-a-cent pricing unlocks new business models for",
    "     AI agents and autonomous software systems.",
  ],
  [
    "  1. USDC: A Digital Dollar for the Global Economy",
    "     https://www.circle.com/usdc",
    "     USDC is a fully reserved stablecoin pegged to the US dollar,",
    "     redeemable 1:1 for USD, and available on multiple blockchains.",
    "",
    "  2. Stablecoin Payment Rails for B2B Commerce",
    "     https://www.coindesk.com/stablecoin-b2b-payments",
    "     Enterprise adoption of stablecoins for cross-border payments",
    "     grew 240% in 2025 as settlement costs dropped to near zero.",
    "",
    "  3. Tempo Network — Programmable Payments",
    "     https://tempo.xyz/docs",
    "     Tempo is a purpose-built chain for real-time payments with",
    "     sub-second finality and native stablecoin support.",
  ],
  [
    "  1. Building AI Agents That Pay for Themselves",
    "     https://openai.com/research/agent-payments",
    "     How autonomous agents can use payment protocols to access APIs,",
    "     compute resources, and data without human intervention.",
    "",
    "  2. The Agentic Web: Machines as Economic Actors",
    "     https://www.wired.com/story/agentic-web-economy",
    "     A new generation of AI systems is emerging that can negotiate,",
    "     transact, and settle payments in real time.",
    "",
    "  3. MCP and the Future of Tool Use",
    "     https://modelcontextprotocol.io/introduction",
    "     The Model Context Protocol standardizes how AI models interact",
    "     with external tools, APIs, and data sources.",
  ],
  [
    "  1. EIP-4337: Account Abstraction for Everyone",
    "     https://eips.ethereum.org/EIPS/eip-4337",
    "     Account abstraction decouples validation from execution, enabling",
    "     smart contract wallets and gasless transactions.",
    "",
    "  2. Payment Channels: Off-Chain Scaling",
    "     https://ethereum.org/en/developers/docs/scaling/payment-channels",
    "     Payment channels allow thousands of transactions between two",
    "     parties with only two on-chain settlements.",
    "",
    "  3. State of Stablecoins Report 2025",
    "     https://www.chainalysis.com/stablecoins-2025",
    "     Stablecoin transaction volume surpassed Visa in Q3 2025, driven",
    "     by programmatic payments and DeFi settlement.",
  ],
  [
    "  1. REST API Design: Pricing and Rate Limiting",
    "     https://blog.postman.com/api-pricing-patterns",
    "     Common monetization strategies for APIs including freemium tiers,",
    "     pay-per-call, and usage-based billing models.",
    "",
    "  2. The End of API Keys",
    "     https://www.fastcompany.com/end-of-api-keys",
    "     How payment-based authentication eliminates the need for static",
    "     API keys, reducing credential leaks and abuse.",
    "",
    "  3. WebAuthn Meets Payments",
    "     https://w3c.github.io/webauthn-payments",
    "     A W3C draft exploring how passkeys and biometric auth can be",
    "     combined with payment authorization flows.",
  ],
];

export const ARTICLE_SUMMARIES = [
  [
    "The article argues that HTTP 402 has been dormant for 30 years because",
    "no payment rail was fast or cheap enough to make per-request pricing",
    "viable. Stablecoins on high-throughput chains finally change that.",
    "MPP provides the missing protocol layer between HTTP and on-chain settlement.",
  ],
  [
    "Researchers at Stanford found that AI agents equipped with payment",
    "capabilities completed 3.2x more tasks than agents without them.",
    "The bottleneck was not intelligence but access—agents couldn't pay",
    "for premium data sources, compute, or third-party APIs.",
  ],
  [
    "Circle reported that USDC on-chain transfer volume reached $12 trillion",
    "in 2025, with programmatic machine-to-machine payments accounting for",
    "18% of total volume. The fastest-growing segment was API micropayments",
    "at sub-cent amounts, growing 400% year-over-year.",
  ],
  [
    "The post explains how payment channels work: two parties lock funds",
    "in a smart contract, exchange signed balance updates off-chain, and",
    "settle the final state on-chain. This amortizes gas costs across",
    "thousands of transactions, making sub-cent payments economically viable.",
    "The author benchmarks a channel processing 10,000 API calls for $0.02 in gas.",
  ],
  [
    "Tempo launched its mainnet with sub-second finality and transaction",
    "fees under $0.0001. The chain is purpose-built for payments, with",
    "native USDC and USDT support. Early adopters include three major",
    "AI inference providers and a dozen API marketplaces.",
  ],
];
