export const SPINNER_FRAMES = [
  "⠋",
  "⠙",
  "⠹",
  "⠸",
  "⠼",
  "⠴",
  "⠦",
  "⠧",
  "⠇",
  "⠏",
];

export const CHAT_RESPONSES = [
  [
    "HTTP 402 is the status code for Payment Required. It was reserved in",
    "HTTP/1.1 but never standardized—until now. MPP defines a challenge-",
    "credential-receipt flow that lets any API monetize with stablecoins.",
    "The server sends a WWW-Authenticate challenge, the client signs a",
    "payment credential, and the server returns a receipt on success.",
    "No API keys, no billing portals, no invoices. Just pay-per-request.",
  ],
  [
    "Micropayments change the economics of APIs. Instead of monthly",
    "subscriptions with usage limits, you pay fractions of a cent per",
    "request. A single GPT-4o call costs about $0.003. An image gen",
    "costs $0.01. Web search is $0.002. The marginal cost is so low",
    "that agents can autonomously decide what to pay for.",
  ],
  [
    "Stablecoins like USDC solve the payment rail problem. They settle",
    "in seconds, cost almost nothing to transfer, and work globally",
    "without bank accounts or currency conversion. When you combine",
    "stablecoins with HTTP-native auth, you get a protocol where any",
    "machine can pay any other machine, anywhere, instantly.",
  ],
  [
    "The key insight is that AI agents need to pay for things. They call",
    "APIs, use compute, fetch data—but they can't enter credit card",
    "numbers. MPP gives agents a wallet and a protocol. The agent signs",
    "a payment, the server verifies it on-chain, and the response streams",
    "back. No human in the loop.",
  ],
  [
    "Payment channels let you batch thousands of micropayments into a",
    "single on-chain settlement. You open a channel, make requests, and",
    "each one increments a signed balance. When you're done, the final",
    "balance settles on-chain. One transaction for a thousand API calls.",
    "Gas costs amortized to nearly zero.",
  ],
  [
    "Think of it like this: every API endpoint has a price, just like",
    "every webpage has a URL. The price lives in the 402 response header.",
    "Clients that understand the protocol pay automatically. Clients that",
    "don't get a standard HTTP error. It's backwards-compatible with the",
    "entire web. No new infrastructure required.",
  ],
  [
    "The authorization header carries a signed payment credential. The",
    "server verifies the signature, checks the amount, and processes the",
    "request. If the payment is valid, you get a 200 with a receipt",
    "header. If not, you get a 402 with a challenge. The whole exchange",
    "takes milliseconds—faster than a credit card authorization.",
  ],
];

export const IMAGE_RESULTS = [
  ["https://picsum.photos/seed/mpp-image-0/400/400"],
  ["https://picsum.photos/seed/mpp-image-1/400/400"],
  ["https://picsum.photos/seed/mpp-image-2/400/400"],
  ["https://picsum.photos/seed/mpp-image-3/400/400"],
  ["https://picsum.photos/seed/mpp-image-4/400/400"],
];

export const POEM_RESULTS = [
  [
    "In circuits deep where data streams,",
    "A payment flows like whispered dreams,",
    "No card, no form, no human hand—",
    "Just code that speaks, and coins that land.",
    "The wallet signs without a sound,",
    "A fraction spent, a verse is found.",
    "No ledger clerk, no bank in sight,",
    "Just protocol and cryptic light.",
    "The merchant nods, the stream flows on,",
    "A micropayment here, then gone.",
  ],
  [
    "A merchant waits behind a gate,",
    "Four-oh-two, the price of fate.",
    "A coin slides through the wire thin,",
    "The door swings wide — the stream begins.",
    "Each byte that passes, paid in kind,",
    "A trustless deal, by code designed.",
    "No middleman to claim a share,",
    "Just sender, service, open air.",
    "The channel hums from end to end,",
    "A cent to spend, a thought to send.",
  ],
  [
    "Ones and zeros, wallets hum,",
    "Micro-pennies, here they come.",
    "Each token spent, a verse returned,",
    "A fair exchange, autonomously earned.",
    "The wire sings a quiet tune,",
    "A stablecoin beneath the moon.",
    "No invoice filed, no receipt lost,",
    "The chain remembers every cost.",
    "From node to node the signal flies,",
    "A paid-for truth that never lies.",
  ],
  [
    "No invoice sent, no bill to pay,",
    "The protocol knows the way.",
    "A handshake signed in cryptic light,",
    "Two machines agree: the price is right.",
    "The voucher lands, the balance shifts,",
    "A stream of data onward drifts.",
    "No human hand to slow the pace,",
    "Just math and trust in empty space.",
    "The escrow holds, the channel clears,",
    "A settlement in milliseconds, not years.",
  ],
  [
    "From wallet A to wallet B,",
    "A fraction of a cent runs free.",
    "The API responds in kind,",
    "A paid-for thought, from mind to mind.",
    "The signature was small and tight,",
    "A voucher sealed in morning light.",
    "The server checked, the proof was sound,",
    "And fresh-minted data was found.",
    "No debt accrued, no tab to close,",
    "Just value moving as it flows.",
  ],
  [
    "The ledger hums beneath the wire,",
    "A thousand calls, they never tire.",
    "Each micropayment, signed and sealed,",
    "A trustless bond the chain revealed.",
    "No middleman to slow the trade,",
    "No paper trail, no debt unpaid.",
    "The protocol speaks clear and true—",
    "A cent for me, a byte for you.",
    "The channel opened, tokens flowed,",
    "A silent pact on every road.",
  ],
  [
    "A key was born at half past three,",
    "Derived from entropy and sea.",
    "It signed a channel, locked a bond,",
    "And whispered to the world beyond.",
    "The service answered, line by line,",
    "Each response worth a fraction fine.",
    "When all was spent, the channel closed,",
    "And both sides settled, well-disposed.",
    "No court, no clerk, no arbiter—",
    "Just math, and trust in what they were.",
  ],
];

export const SEARCH_RESULTS = [
  [
    "  1. HTTP 402 Payment Required — MDN Web Docs",
    "     https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402",
    "     The 402 status code is reserved for future use in digital payment",
    "     systems. Originally defined in HTTP/1.1, it was never standardized.",
    "",
    "  2. Machine Payment Protocol Specification",
    "     https://mppx.dev/specs/core",
    "     MPP defines a challenge-credential-receipt flow for HTTP-native",
    "     payments using stablecoins on EVM-compatible chains.",
    "",
    "  3. The Economics of API Micropayments",
    "     https://a]16z.com/micropayments-api-economy",
    "     Why fractions-of-a-cent pricing unlocks new business models for",
    "     AI agents and autonomous software systems.",
  ],
  [
    "  1. USDC: A Digital Dollar for the Global Economy",
    "     https://www.circle.com/usdc",
    "     USDC is a fully reserved stablecoin pegged to the US dollar,",
    "     redeemable 1:1 for USD, and available on multiple blockchains.",
    "",
    "  2. Stablecoin Payment Rails for B2B Commerce",
    "     https://www.coindesk.com/stablecoin-b2b-payments",
    "     Enterprise adoption of stablecoins for cross-border payments",
    "     grew 240% in 2025 as settlement costs dropped to near zero.",
    "",
    "  3. Tempo Network — Programmable Payments",
    "     https://tempo.xyz/docs",
    "     Tempo is a purpose-built chain for real-time payments with",
    "     sub-second finality and native stablecoin support.",
  ],
  [
    "  1. Building AI Agents That Pay for Themselves",
    "     https://openai.com/research/agent-payments",
    "     How autonomous agents can use payment protocols to access APIs,",
    "     compute resources, and data without human intervention.",
    "",
    "  2. The Agentic Web: Machines as Economic Actors",
    "     https://www.wired.com/story/agentic-web-economy",
    "     A new generation of AI systems is emerging that can negotiate,",
    "     transact, and settle payments in real time.",
    "",
    "  3. MCP and the Future of Tool Use",
    "     https://modelcontextprotocol.io/introduction",
    "     The Model Context Protocol standardizes how AI models interact",
    "     with external tools, APIs, and data sources.",
  ],
  [
    "  1. EIP-4337: Account Abstraction for Everyone",
    "     https://eips.ethereum.org/EIPS/eip-4337",
    "     Account abstraction decouples validation from execution, enabling",
    "     smart contract wallets and gasless transactions.",
    "",
    "  2. Payment Channels: Off-Chain Scaling",
    "     https://ethereum.org/en/developers/docs/scaling/payment-channels",
    "     Payment channels allow thousands of transactions between two",
    "     parties with only two on-chain settlements.",
    "",
    "  3. State of Stablecoins Report 2025",
    "     https://www.chainalysis.com/stablecoins-2025",
    "     Stablecoin transaction volume surpassed Visa in Q3 2025, driven",
    "     by programmatic payments and DeFi settlement.",
  ],
  [
    "  1. REST API Design: Pricing and Rate Limiting",
    "     https://blog.postman.com/api-pricing-patterns",
    "     Common monetization strategies for APIs including freemium tiers,",
    "     pay-per-call, and usage-based billing models.",
    "",
    "  2. The End of API Keys",
    "     https://www.fastcompany.com/end-of-api-keys",
    "     How payment-based authentication eliminates the need for static",
    "     API keys, reducing credential leaks and abuse.",
    "",
    "  3. WebAuthn Meets Payments",
    "     https://w3c.github.io/webauthn-payments",
    "     A W3C draft exploring how passkeys and biometric auth can be",
    "     combined with payment authorization flows.",
  ],
];

export const ARTICLE_SUMMARIES = [
  [
    "The article argues that HTTP 402 has been dormant for 30 years because",
    "no payment rail was fast or cheap enough to make per-request pricing",
    "viable. Stablecoins on high-throughput chains finally change that.",
    "MPP provides the missing protocol layer between HTTP and on-chain settlement.",
  ],
  [
    "Researchers at Stanford found that AI agents equipped with payment",
    "capabilities completed 3.2x more tasks than agents without them.",
    "The bottleneck was not intelligence but access—agents couldn't pay",
    "for premium data sources, compute, or third-party APIs.",
  ],
  [
    "Circle reported that USDC on-chain transfer volume reached $12 trillion",
    "in 2025, with programmatic machine-to-machine payments accounting for",
    "18% of total volume. The fastest-growing segment was API micropayments",
    "at sub-cent amounts, growing 400% year-over-year.",
  ],
  [
    "The post explains how payment channels work: two parties lock funds",
    "in a smart contract, exchange signed balance updates off-chain, and",
    "settle the final state on-chain. This amortizes gas costs across",
    "thousands of transactions, making sub-cent payments economically viable.",
    "The author benchmarks a channel processing 10,000 API calls for $0.02 in gas.",
  ],
  [
    "Tempo launched its mainnet with sub-second finality and transaction",
    "fees under $0.0001. The chain is purpose-built for payments, with",
    "native USDC and USDT support. Early adopters include three major",
    "AI inference providers and a dozen API marketplaces.",
  ],
];
